# Site settings
 title: Georgy Georgieff
 description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
 url: "georgy.georgieff.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Georgy Georgieff
user_description: I\'m a Junior Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately 
user_title: Software Engineer
email: georgy.georgieff@gmail.com


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
