# Site settings
title: Georgy Georgieff
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: localhost:3000 # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Georgy Georgieff
user_description: may be later ;-)
user_title: Junior Software Developer
email: Georgy.Georgieff@gmail.com
#linkedin_username: junjiwiener
#github_username: 8Jun
#reddit_username: BATTLECATHOTS

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
